### ISSUE TITLE
<BE> Repository의 메소드명 수정

### ISSUE THREAD

**Issue by Choi-JY1107** [boostcampwm-2024/web24-GOMZ#175]
## task

Repository의 메소드명 수정

## 예상 소요 시간

- 30분

### study-room
`createRoom` : 방 생성 메소드 -> `saveRoom`으로 수정
`getRooms` : 모든 방 조회 메소드 -> `findAllRooms`로 수정
`findRoom` : Id를 기반으로 방을 찾는 메소드 -> `findRoomById`로 수정

### study-room-participant
`addUserToRoom` : 참가자 추가 메소드 -> `saveParticipant`으로 수정
`findParticipant` : 소켓 ID로 사용자 조회 메소드 -> `findParticipantBySocketId`로 수정
`removeUserFromRoom` : 사용자 제거 메소드 -> `deleteParticipantBySocketId`로 수정
`getRoomUsers` : 특정 방의 모든 사용자 조회 메소드 -> `findParticipantsByRoomId`로 수정
`leaveAllRooms` : 모든 방에서 특정 사용자 제거 메소드 -> 삭제
`getAllRooms` : 모든 방 정보 조회 메소드 -> 수정, 소켓 ID로 방 조회 메소드, `findRoomIdBySocketId`

## 완료 조건
- [x] 동사를 CRUD에 맞게 하였는가?
  - CREATE : `add`
  - READ : `find`
  - UPDATE : `update`
  - DELETE : `delete`

- [x] 조건 추가 시 by로 조건을 추가하였는가?
  - 예시 : roomId로 room을 찾는다면 -> `findRoomById`

- [x] 복수 데이터는 복수형으로 반환하였는가?

- [x] 서비스 로직의 메소드의 반환값은 전혀 건드리지 않았는가?
